// Auto-generated from Gametora skills data
// Run: node scripts/parse-skills.js

export interface SkillData {
    id: number;
    name: string;
    description: string;
    isUnique?: boolean;
    uniqueFor?: string;
}

export const SKILL_DICT: Record<number, SkillData> = {
    200011: { id: 200011, name: 'Right-Handed ◎', description: 'Increase performance on right-handed tracks.', isUnique: false, uniqueFor: '' },
    200012: { id: 200012, name: 'Right-Handed ○', description: 'Moderately increase performance on right-handed tracks.', isUnique: false, uniqueFor: '' },
    200021: { id: 200021, name: 'Left-Handed ◎', description: 'Increase performance on left-handed tracks.', isUnique: false, uniqueFor: '' },
    200022: { id: 200022, name: 'Left-Handed ○', description: 'Moderately increase performance on left-handed tracks.', isUnique: false, uniqueFor: '' },
    200171: { id: 200171, name: 'Spring Runner ◎', description: 'Increase performance in spring.', isUnique: false, uniqueFor: '' },
    200172: { id: 200172, name: 'Spring Runner ○', description: 'Moderately increase performance in spring.', isUnique: false, uniqueFor: '' },
    200181: { id: 200181, name: 'Summer Runner ◎', description: 'Increase performance in summer.', isUnique: false, uniqueFor: '' },
    200182: { id: 200182, name: 'Summer Runner ○', description: 'Moderately increase performance in summer.', isUnique: false, uniqueFor: '' },
    200191: { id: 200191, name: 'Fall Runner ◎', description: 'Increase performance in fall.', isUnique: false, uniqueFor: '' },
    200192: { id: 200192, name: 'Fall Runner ○', description: 'Moderately increase performance in fall.', isUnique: false, uniqueFor: '' },
    200201: { id: 200201, name: 'Winter Runner ◎', description: 'Increase performance in winter.', isUnique: false, uniqueFor: '' },
    200202: { id: 200202, name: 'Winter Runner ○', description: 'Moderately increase performance in winter.', isUnique: false, uniqueFor: '' },
    200261: { id: 200261, name: 'Outer Post Proficiency ◎', description: 'Increase performance in brackets 6–8.', isUnique: false, uniqueFor: '' },
    200262: { id: 200262, name: 'Outer Post Proficiency ○', description: 'Moderately increase performance in brackets 6–8.', isUnique: false, uniqueFor: '' },
    200271: { id: 200271, name: 'Maverick ◎', description: 'Greatly increase performance when no other runners are using the same strategy.', isUnique: false, uniqueFor: '' },
    200272: { id: 200272, name: 'Maverick ○', description: 'Increase performance when no other runners are using the same strategy.', isUnique: false, uniqueFor: '' },
    200301: { id: 200301, name: 'Long Shot ◎', description: 'Increase performance when 4th favorite or below.', isUnique: false, uniqueFor: '' },
    200302: { id: 200302, name: 'Long Shot ○', description: 'Moderately increase performance when 4th favorite or below.', isUnique: false, uniqueFor: '' },
    201631: { id: 201631, name: 'Sympathy', description: 'Moderately increase performance when many runners share a sympathetic heart.', isUnique: false, uniqueFor: '' },
    201641: { id: 201641, name: 'Lone Wolf', description: 'Moderately increase performance when no other runners have the heart of a lone wolf.', isUnique: false, uniqueFor: '' },
    300031: { id: 300031, name: 'Towards the Scenery I Seek', description: 'Moderately increase performance in pursuit of that long sought-after scenery.', isUnique: false, uniqueFor: '' },
    300071: { id: 300071, name: 'Show Me What Lies Beyond!', description: 'Moderately increase Silence Suzuka\'s performance thanks to the desire to see her running reach new heights.', isUnique: false, uniqueFor: '' },
    300111: { id: 300111, name: 'Chin Up, Derby Umamusume!', description: 'Feel closer to being Japan\'s top racer, moderately increasing performance.', isUnique: false, uniqueFor: '' },
    300021: { id: 300021, name: 'Unchanging', description: 'Greatly increase performance with the same ambition of days past.', isUnique: false, uniqueFor: '' },
    200194: { id: 200194, name: 'Fall Frenzy', description: 'Increase performance in fall, boosting Speed and Power.', isUnique: false, uniqueFor: '' },
    200174: { id: 200174, name: 'Spring Spectacle', description: 'Increase performance in spring, boosting Speed and Power.', isUnique: false, uniqueFor: '' },
    200014: { id: 200014, name: 'Right-Handed Demon', description: 'Increase proficiency in right-handed tracks, increasing Speed and Power.', isUnique: false, uniqueFor: '' },
    200013: { id: 200013, name: 'Right-Handed ×', description: 'Moderately decrease performance on right-handed tracks.', isUnique: false, uniqueFor: '' },
    200023: { id: 200023, name: 'Left-Handed ×', description: 'Moderately decrease performance on left-handed tracks.', isUnique: false, uniqueFor: '' },
    200173: { id: 200173, name: 'Spring Runner ×', description: 'Moderately decrease performance in spring.', isUnique: false, uniqueFor: '' },
    200183: { id: 200183, name: 'Summer Runner ×', description: 'Moderately decrease performance in summer.', isUnique: false, uniqueFor: '' },
    200193: { id: 200193, name: 'Fall Runner ×', description: 'Moderately decrease performance in fall.', isUnique: false, uniqueFor: '' },
    200203: { id: 200203, name: 'Winter Runner ×', description: 'Moderately decrease performance in winter.', isUnique: false, uniqueFor: '' },
    200263: { id: 200263, name: 'Outer Post Averseness', description: 'Moderately decrease performance in brackets 6–8.', isUnique: false, uniqueFor: '' },
    200311: { id: 200311, name: 'G1 Averseness', description: 'Moderately decrease performance in G1 or otherwise important races.', isUnique: false, uniqueFor: '' },
    201801: { id: 201801, name: '♡ 3D Nail Art', description: 'Moderately decrease performance on firm ground.', isUnique: false, uniqueFor: '' },
    300041: { id: 300041, name: 'Creeping Anxiety', description: 'Moderately decrease performance due to Trainer\'s anxiety.', isUnique: false, uniqueFor: '' },
    200031: { id: 200031, name: 'Tokyo Racecourse ◎', description: 'Increase performance at Tokyo Racecourse.', isUnique: false, uniqueFor: '' },
    200032: { id: 200032, name: 'Tokyo Racecourse ○', description: 'Moderately increase performance at Tokyo Racecourse.', isUnique: false, uniqueFor: '' },
    200041: { id: 200041, name: 'Nakayama Racecourse ◎', description: 'Increase performance at Nakayama Racecourse.', isUnique: false, uniqueFor: '' },
    200042: { id: 200042, name: 'Nakayama Racecourse ○', description: 'Moderately increase performance at Nakayama Racecourse.', isUnique: false, uniqueFor: '' },
    200051: { id: 200051, name: 'Hanshin Racecourse ◎', description: 'Increase performance at Hanshin Racecourse.', isUnique: false, uniqueFor: '' },
    200052: { id: 200052, name: 'Hanshin Racecourse ○', description: 'Moderately increase performance at Hanshin Racecourse.', isUnique: false, uniqueFor: '' },
    200061: { id: 200061, name: 'Kyoto Racecourse ◎', description: 'Increase performance at Kyoto Racecourse.', isUnique: false, uniqueFor: '' },
    200062: { id: 200062, name: 'Kyoto Racecourse ○', description: 'Moderately increase performance at Kyoto Racecourse.', isUnique: false, uniqueFor: '' },
    200071: { id: 200071, name: 'Chukyo Racecourse ◎', description: 'Increase performance at Chukyo Racecourse.', isUnique: false, uniqueFor: '' },
    200072: { id: 200072, name: 'Chukyo Racecourse ○', description: 'Moderately increase performance at Chukyo Racecourse.', isUnique: false, uniqueFor: '' },
    200081: { id: 200081, name: 'Sapporo Racecourse ◎', description: 'Increase performance at Sapporo Racecourse.', isUnique: false, uniqueFor: '' },
    200082: { id: 200082, name: 'Sapporo Racecourse ○', description: 'Moderately increase performance at Sapporo Racecourse.', isUnique: false, uniqueFor: '' },
    200091: { id: 200091, name: 'Hakodate Racecourse ◎', description: 'Increase performance at Hakodate Racecourse.', isUnique: false, uniqueFor: '' },
    200092: { id: 200092, name: 'Hakodate Racecourse ○', description: 'Moderately increase performance at Hakodate Racecourse.', isUnique: false, uniqueFor: '' },
    200101: { id: 200101, name: 'Fukushima Racecourse ◎', description: 'Increase performance at Fukushima Racecourse.', isUnique: false, uniqueFor: '' },
    200102: { id: 200102, name: 'Fukushima Racecourse ○', description: 'Moderately increase performance at Fukushima Racecourse.', isUnique: false, uniqueFor: '' },
    200111: { id: 200111, name: 'Niigata Racecourse ◎', description: 'Increase performance at Niigata Racecourse.', isUnique: false, uniqueFor: '' },
    200112: { id: 200112, name: 'Niigata Racecourse ○', description: 'Moderately increase performance at Niigata Racecourse.', isUnique: false, uniqueFor: '' },
    200121: { id: 200121, name: 'Kokura Racecourse ◎', description: 'Increase performance at Kokura Racecourse.', isUnique: false, uniqueFor: '' },
    200122: { id: 200122, name: 'Kokura Racecourse ○', description: 'Moderately increase performance at Kokura Racecourse.', isUnique: false, uniqueFor: '' },
    200131: { id: 200131, name: 'Standard Distance ◎', description: 'Increase performance over standard distances (multiples of 400m).', isUnique: false, uniqueFor: '' },
    200132: { id: 200132, name: 'Standard Distance ○', description: 'Moderately increase performance over standard distances (multiples of 400m).', isUnique: false, uniqueFor: '' },
    200141: { id: 200141, name: 'Non-Standard Distance ◎', description: 'Increase performance over non-standard distances (non-multiples of 400m).', isUnique: false, uniqueFor: '' },
    200142: { id: 200142, name: 'Non-Standard Distance ○', description: 'Moderately increase performance over non-standard distances (non-multiples of 400m).', isUnique: false, uniqueFor: '' },
    200951: { id: 200951, name: 'Oi Racecourse ◎', description: 'Increase performance at Oi Racecourse.', isUnique: false, uniqueFor: '' },
    200952: { id: 200952, name: 'Oi Racecourse ○', description: 'Moderately increase performance at Oi Racecourse.', isUnique: false, uniqueFor: '' },
    300011: { id: 300011, name: 'Unquenched Thirst', description: 'Moderately increase performance with the desire to race.', isUnique: false, uniqueFor: '' },
    300081: { id: 300081, name: 'Hoiya! Have a Good Run!', description: 'Moderately increase Silence Suzuka\'s performance thanks to a charm that guarantees a satisfying run.', isUnique: false, uniqueFor: '' },
    1200021: { id: 1200021, name: 'Long Race Enthusiast', description: 'Increase performance in Long Turf races. This skill is exclusive to the event.', isUnique: false, uniqueFor: '' },
    200064: { id: 200064, name: 'Yodo Invicta', description: 'Increase performance at Kyoto Racecourse, boosting Stamina and Wit.', isUnique: false, uniqueFor: '' },
    300121: { id: 300121, name: 'For the Team', description: 'The whole team feels super determined to win this special race, greatly increasing performance.', isUnique: false, uniqueFor: '' },
    200033: { id: 200033, name: 'Tokyo Racecourse ×', description: 'Moderately decrease performance at Tokyo Racecourse.', isUnique: false, uniqueFor: '' },
    200043: { id: 200043, name: 'Nakayama Racecourse ×', description: 'Moderately decrease performance at Nakayama Racecourse.', isUnique: false, uniqueFor: '' },
    200053: { id: 200053, name: 'Hanshin Racecourse ×', description: 'Moderately decrease performance at Hanshin Racecourse.', isUnique: false, uniqueFor: '' },
    200063: { id: 200063, name: 'Kyoto Racecourse ×', description: 'Moderately decrease performance at Kyoto Racecourse.', isUnique: false, uniqueFor: '' },
    200073: { id: 200073, name: 'Chukyo Racecourse ×', description: 'Moderately decrease performance at Chukyo Racecourse.', isUnique: false, uniqueFor: '' },
    200083: { id: 200083, name: 'Sapporo Racecourse ×', description: 'Moderately decrease performance at Sapporo Racecourse.', isUnique: false, uniqueFor: '' },
    200093: { id: 200093, name: 'Hakodate Racecourse ×', description: 'Moderately decrease performance at Hakodate Racecourse.', isUnique: false, uniqueFor: '' },
    200103: { id: 200103, name: 'Fukushima Racecourse ×', description: 'Moderately decrease performance at Fukushima Racecourse.', isUnique: false, uniqueFor: '' },
    200113: { id: 200113, name: 'Niigata Racecourse ×', description: 'Moderately decrease performance at Niigata Racecourse.', isUnique: false, uniqueFor: '' },
    200123: { id: 200123, name: 'Kokura Racecourse ×', description: 'Moderately decrease performance at Kokura Racecourse.', isUnique: false, uniqueFor: '' },
    200133: { id: 200133, name: 'Standard Distance ×', description: 'Moderately decrease performance over standard distances (multiples of 400m).', isUnique: false, uniqueFor: '' },
    200143: { id: 200143, name: 'Non-Standard Distance ×', description: 'Moderately decrease performance over non-standard distances (non-multiples of 400m).', isUnique: false, uniqueFor: '' },
    200321: { id: 200321, name: 'Paddock Fright', description: 'Moderately decrease performance when the favorite.', isUnique: false, uniqueFor: '' },
    200953: { id: 200953, name: 'Oi Racecourse ×', description: 'Moderately decrease performance at Oi Racecourse.', isUnique: false, uniqueFor: '' },
    200151: { id: 200151, name: 'Firm Conditions ◎', description: 'Increase performance on firm ground.', isUnique: false, uniqueFor: '' },
    200152: { id: 200152, name: 'Firm Conditions ○', description: 'Moderately increase performance on firm ground.', isUnique: false, uniqueFor: '' },
    200161: { id: 200161, name: 'Wet Conditions ◎', description: 'Increase performance on good, soft, and heavy ground.', isUnique: false, uniqueFor: '' },
    200162: { id: 200162, name: 'Wet Conditions ○', description: 'Moderately increase performance on good, soft, and heavy ground.', isUnique: false, uniqueFor: '' },
    200281: { id: 200281, name: 'Competitive Spirit ◎', description: 'Increase performance when many other runners are using the same strategy.', isUnique: false, uniqueFor: '' },
    200282: { id: 200282, name: 'Competitive Spirit ○', description: 'Moderately increase performance when many other runners are using the same strategy.', isUnique: false, uniqueFor: '' },
    300091: { id: 300091, name: 'As a Friend and Rival', description: 'Moderately increase Silence Suzuka\'s performance through the happiness felt seeing a friend find their running style.', isUnique: false, uniqueFor: '' },
    1200031: { id: 1200031, name: 'Mile Race Enthusiast', description: 'Increase performance in Mile Turf races. This skill is exclusive to the event.', isUnique: false, uniqueFor: '' },
    200154: { id: 200154, name: 'Firm Course Menace', description: 'Increase performance on firm ground, boosting Power and Speed.', isUnique: false, uniqueFor: '' },
    200153: { id: 200153, name: 'Firm Conditions ×', description: 'Moderately decrease performance on firm ground.', isUnique: false, uniqueFor: '' },
    200163: { id: 200163, name: 'Wet Conditions ×', description: 'Moderately decrease performance on good, soft, and heavy ground.', isUnique: false, uniqueFor: '' },
    200283: { id: 200283, name: 'Wallflower', description: 'Moderately decrease performance when many other runners are using the same strategy.', isUnique: false, uniqueFor: '' },
    200211: { id: 200211, name: 'Sunny Days ◎', description: 'Increase performance in sunny weather.', isUnique: false, uniqueFor: '' },
    200212: { id: 200212, name: 'Sunny Days ○', description: 'Moderately increase performance in sunny weather.', isUnique: false, uniqueFor: '' },
    200221: { id: 200221, name: 'Cloudy Days ◎', description: 'Increase performance in cloudy weather.', isUnique: false, uniqueFor: '' },
    200222: { id: 200222, name: 'Cloudy Days ○', description: 'Moderately increase performance in cloudy weather.', isUnique: false, uniqueFor: '' },
    200231: { id: 200231, name: 'Rainy Days ◎', description: 'Increase performance in rainy weather.', isUnique: false, uniqueFor: '' },
    200232: { id: 200232, name: 'Rainy Days ○', description: 'Moderately increase performance in rainy weather.', isUnique: false, uniqueFor: '' },
    200241: { id: 200241, name: 'Snowy Days ◎', description: 'Increase performance in snowy weather.', isUnique: false, uniqueFor: '' },
    200242: { id: 200242, name: 'Snowy Days ○', description: 'Moderately increase performance in snowy weather.', isUnique: false, uniqueFor: '' },
    200291: { id: 200291, name: 'Target in Sight ◎', description: 'Increase performance when the favorite is using the same strategy.', isUnique: false, uniqueFor: '' },
    200292: { id: 200292, name: 'Target in Sight ○', description: 'Moderately increase performance when the favorite is using the same strategy.', isUnique: false, uniqueFor: '' },
    200233: { id: 200233, name: 'Rainy Days ×', description: 'Moderately decrease performance in rainy weather.', isUnique: false, uniqueFor: '' },
    202181: { id: 202181, name: '99 Problems', description: 'Get overwhelmed by powerful opponents, moderately decreasing Guts and Wit.', isUnique: false, uniqueFor: '' },
    200251: { id: 200251, name: 'Inner Post Proficiency ◎', description: 'Increase performance in brackets 1–3.', isUnique: false, uniqueFor: '' },
    200252: { id: 200252, name: 'Inner Post Proficiency ○', description: 'Moderately increase performance in brackets 1–3.', isUnique: false, uniqueFor: '' },
    201521: { id: 201521, name: 'Front Runner Savvy ◎', description: 'Increase ability to get into a good position. (Front Runner)', isUnique: false, uniqueFor: '' },
    201522: { id: 201522, name: 'Front Runner Savvy ○', description: 'Moderately increase ability to get into a good position. (Front Runner)', isUnique: false, uniqueFor: '' },
    201531: { id: 201531, name: 'Pace Chaser Savvy ◎', description: 'Increase ability to get into a good position. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201532: { id: 201532, name: 'Pace Chaser Savvy ○', description: 'Moderately increase ability to get into a good position. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201541: { id: 201541, name: 'Late Surger Savvy ◎', description: 'Increase ability to get into a good position. (Late Surger)', isUnique: false, uniqueFor: '' },
    201542: { id: 201542, name: 'Late Surger Savvy ○', description: 'Moderately increase ability to get into a good position. (Late Surger)', isUnique: false, uniqueFor: '' },
    201551: { id: 201551, name: 'End Closer Savvy ◎', description: 'Increase ability to get into a good position. (End Closer)', isUnique: false, uniqueFor: '' },
    201552: { id: 201552, name: 'End Closer Savvy ○', description: 'Moderately increase ability to get into a good position. (End Closer)', isUnique: false, uniqueFor: '' },
    202161: { id: 202161, name: 'Restraint', description: 'Increase Wit and moderately decrease the chance of being Rushed.', isUnique: false, uniqueFor: '' },
    1200011: { id: 1200011, name: 'Medium Race Enthusiast', description: 'Increase performance in Medium Turf races. This skill is exclusive to the event.', isUnique: false, uniqueFor: '' },
    200253: { id: 200253, name: 'Inner Post Averseness', description: 'Moderately decrease performance in brackets 1–3.', isUnique: false, uniqueFor: '' },
    201562: { id: 201562, name: 'Lucky Seven', description: 'Moderately good things may happen when in bracket 7.', isUnique: false, uniqueFor: '' },
    201561: { id: 201561, name: 'Super Lucky Seven', description: 'Good things may happen when in bracket 7.', isUnique: false, uniqueFor: '' },
    10321: { id: 10321, name: 'Introduction to Physiology', description: 'Moderately recover endurance and slightly increase velocity for a moderate duration when sitting off the pace on a corner in the second half of the race.', isUnique: true, uniqueFor: 'Agnes Tachyon (Original)' },
    10451: { id: 10451, name: 'Clear Heart', description: 'Recover endurance when well-positioned mid-race.', isUnique: true, uniqueFor: 'Super Creek (Original)' },
    10521: { id: 10521, name: 'Super-Duper Stoked', description: 'Moderately recover endurance with a glance at nearby runners when positioned toward the back on the final corner.', isUnique: true, uniqueFor: 'Haru Urara (Original)' },
    100321: { id: 100321, name: 'U=ma2', description: 'Recover endurance and moderately increase velocity for a moderate duration when sitting off the pace on a corner in the second half of the race.', isUnique: true, uniqueFor: 'Agnes Tachyon (Original)' },
    100451: { id: 100451, name: 'Pure Heart', description: 'Greatly recover endurance when well-positioned mid-race.', isUnique: true, uniqueFor: 'Super Creek (Original)' },
    100521: { id: 100521, name: 'Super-Duper Climax', description: 'Recover endurance with a glance at nearby runners when positioned toward the back on the final corner.', isUnique: true, uniqueFor: 'Haru Urara (Original)' },
    200351: { id: 200351, name: 'Swinging Maestro', description: 'Recover endurance on a corner with efficient turning.', isUnique: false, uniqueFor: '' },
    200352: { id: 200352, name: 'Corner Recovery ○', description: 'Slightly recover endurance on a corner with efficient turning.', isUnique: false, uniqueFor: '' },
    200353: { id: 200353, name: 'Corner Recovery ×', description: 'Moderately lose endurance on a corner with inefficient turning.', isUnique: false, uniqueFor: '' },
    200381: { id: 200381, name: 'Breath of Fresh Air', description: 'Recover endurance on a straight.', isUnique: false, uniqueFor: '' },
    200382: { id: 200382, name: 'Straightaway Recovery', description: 'Slightly recover endurance on a straight.', isUnique: false, uniqueFor: '' },
    200391: { id: 200391, name: 'Ramp Revulsion', description: 'Moderately increase fatigue on an uphill.', isUnique: false, uniqueFor: '' },
    200401: { id: 200401, name: 'Packphobia', description: 'Moderately lose endurance when surrounded.', isUnique: false, uniqueFor: '' },
    200441: { id: 200441, name: 'Iron Will', description: 'Recover endurance when the way ahead is jammed early-race or mid-race.', isUnique: false, uniqueFor: '' },
    200442: { id: 200442, name: 'Lay Low', description: 'Slightly recover endurance when the way ahead is jammed early-race or mid-race.', isUnique: false, uniqueFor: '' },
    200471: { id: 200471, name: 'Indomitable', description: 'Recover endurance when passed by another runner mid-race.', isUnique: false, uniqueFor: '' },
    200472: { id: 200472, name: 'Pace Strategy', description: 'Slightly recover endurance when passed by another runner mid-race.', isUnique: false, uniqueFor: '' },
    200481: { id: 200481, name: 'Unruffled', description: 'Recover endurance when surrounded mid-race.', isUnique: false, uniqueFor: '' },
    200482: { id: 200482, name: 'Calm in a Crowd', description: 'Slightly recover endurance when surrounded mid-race.', isUnique: false, uniqueFor: '' },
    200521: { id: 200521, name: 'Running Idle', description: 'Moderately increase fatigue when in the lead by too large of a margin.', isUnique: false, uniqueFor: '' },
    200561: { id: 200561, name: 'Calm and Collected', description: 'Decrease fatigue upon approaching mid-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    200562: { id: 200562, name: 'Stamina to Spare', description: 'Slightly decrease fatigue upon approaching mid-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    200571: { id: 200571, name: 'Race Planner', description: 'Decrease fatigue mid-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    200572: { id: 200572, name: 'Preferred Position', description: 'Slightly decrease fatigue mid-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    200621: { id: 200621, name: 'Sleeping Lion', description: 'Decrease fatigue mid-race. (End Closer)', isUnique: false, uniqueFor: '' },
    200622: { id: 200622, name: 'Standing By', description: 'Slightly decrease fatigue mid-race. (End Closer)', isUnique: false, uniqueFor: '' },
    200662: { id: 200662, name: 'Wait-and-See', description: 'Slightly decrease fatigue and very slightly increase acceleration when positioned toward the back mid-race. (Sprint)', isUnique: false, uniqueFor: '' },
    200691: { id: 200691, name: 'Keen Eye', description: 'Decrease fatigue, then moderately decrease velocity of runners ahead when positioned toward the back upon approaching mid-race. (Mile)', isUnique: false, uniqueFor: '' },
    200692: { id: 200692, name: 'Watchful Eye', description: 'Slightly decrease fatigue, then very slightly decrease velocity of runners ahead when positioned toward the back upon approaching mid-race. (Mile)', isUnique: false, uniqueFor: '' },
    200711: { id: 200711, name: 'Trackblazer', description: 'Decrease fatigue when positioned toward the front mid-race. (Medium)', isUnique: false, uniqueFor: '' },
    200712: { id: 200712, name: 'Rosy Outlook', description: 'Slightly decrease fatigue when positioned toward the front mid-race. (Medium)', isUnique: false, uniqueFor: '' },
    200741: { id: 200741, name: 'Cooldown', description: 'Decrease fatigue by taking a breather upon entering a straight. (Long)', isUnique: false, uniqueFor: '' },
    200742: { id: 200742, name: 'Deep Breaths', description: 'Slightly decrease fatigue by taking a breather upon entering a straight. (Long)', isUnique: false, uniqueFor: '' },
    200761: { id: 200761, name: 'Adrenaline Rush', description: 'Regain the energy to run when close to exhausting strength. (Long)', isUnique: false, uniqueFor: '' },
    200762: { id: 200762, name: 'Extra Tank', description: 'Slightly regain the energy to run when close to exhausting strength. (Long)', isUnique: false, uniqueFor: '' },
    201141: { id: 201141, name: 'Miraculous Step', description: 'Decrease fatigue when moving sideways. (Medium)', isUnique: false, uniqueFor: '' },
    201142: { id: 201142, name: 'Soft Step', description: 'Slightly decrease fatigue when moving sideways. (Medium)', isUnique: false, uniqueFor: '' },
    201202: { id: 201202, name: 'Passing Pro', description: 'Slightly decrease fatigue when determined to pass another runner. (Long)', isUnique: false, uniqueFor: '' },
    201281: { id: 201281, name: 'Restless', description: 'Reduce fatigue on an uphill. (Front Runner)', isUnique: false, uniqueFor: '' },
    201282: { id: 201282, name: 'Moxie', description: 'Slightly reduce fatigue on an uphill. (Front Runner)', isUnique: false, uniqueFor: '' },
    201351: { id: 201351, name: 'Gourmand', description: 'Recover endurance mid-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201352: { id: 201352, name: 'Hydrate', description: 'Slightly recover endurance mid-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201421: { id: 201421, name: 'Relax', description: 'Recover endurance late-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    201422: { id: 201422, name: 'A Small Breather', description: 'Slightly recover endurance late-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    201481: { id: 201481, name: 'Go-Home Specialist', description: 'Reduce fatigue on a downhill. (End Closer)', isUnique: false, uniqueFor: '' },
    201482: { id: 201482, name: 'After-School Stroll', description: 'Slightly reduce fatigue on a downhill. (End Closer)', isUnique: false, uniqueFor: '' },
    201491: { id: 201491, name: 'Serenity', description: 'Regain composure by calming down when the way ahead is jammed. (End Closer)', isUnique: false, uniqueFor: '' },
    201492: { id: 201492, name: 'Levelheaded', description: 'Slightly regain composure by calming down when the way ahead is jammed. (End Closer)', isUnique: false, uniqueFor: '' },
    201571: { id: 201571, name: 'Triple 7s', description: 'Slightly gain energy with 777m remaining.', isUnique: false, uniqueFor: '' },
    201621: { id: 201621, name: 'Shake It Out', description: 'Slightly recover endurance after activating many skills late-race.', isUnique: false, uniqueFor: '' },
    110111: { id: 110111, name: 'Superior Heal', description: 'Greatly recover endurance with a gentle light when overtaken toward the back mid-race.', isUnique: true, uniqueFor: 'Grass Wonder (Fantasy)' },
    110011: { id: 110011, name: 'Dazzl\'n ♪ Diver', description: 'Recover endurance by relaxing after activating 2 skills when positioned midpack mid-race.', isUnique: true, uniqueFor: 'Special Week (Summer)' },
    110301: { id: 110301, name: 'Every Rose Has Its Fangs', description: 'Suck endurance from runners ahead when well-positioned and pressured by another runner mid-race.', isUnique: true, uniqueFor: 'Rice Shower (Halloween)' },
    201691: { id: 201691, name: 'Lie in Wait', description: 'Recover endurance when positioned toward the back upon approaching mid-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    201692: { id: 201692, name: 'Be Still', description: 'Slightly recover endurance when positioned toward the back upon approaching mid-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    201201: { id: 201201, name: 'VIP Pass', description: 'Decrease fatigue when determined to pass another runner. (Long)', isUnique: false, uniqueFor: '' },
    202002: { id: 202002, name: 'Familiar Ground', description: 'Slightly recover endurance when positioned toward the back mid-race. (Dirt)', isUnique: false, uniqueFor: '' },
    300101: { id: 300101, name: 'Cheers of a Fellow Dreamer', description: 'Recover Silence Suzuka\'s endurance on a corner in the second half of the race through a friend\'s cheers of support.', isUnique: false, uniqueFor: '' },
    10621: { id: 10621, name: 'Ready, Go!', description: 'Moderately recover endurance and slightly increase velocity with newfound resolve when in midpack around halfway through the race.', isUnique: true, uniqueFor: 'Matikanetannhauser (Original)' },
    100621: { id: 100621, name: 'Go, Go, Mun!', description: 'Recover endurance and moderately increase velocity with newfound resolve when in midpack around halfway through the race.', isUnique: true, uniqueFor: 'Matikanetannhauser (Original)' },
    202071: { id: 202071, name: 'Of Calm Mind', description: 'If positioned in the midpack around when the mid-race starts, slightly decrease velocity and greatly recover endurance. (Long)', isUnique: false, uniqueFor: '' },
    202072: { id: 202072, name: 'Free-Spirited', description: 'If positioned in the midpack around when the mid-race starts, slightly decrease velocity and moderately recover endurance. (Long)', isUnique: false, uniqueFor: '' },
    100641: { id: 100641, name: 'Keep Pushing Ahead', description: 'If positioned toward the front from the start of the race until the second half of the race, good vibes recover endurance and moderately increase velocity steadily.', isUnique: true, uniqueFor: 'Mejiro Palmer (Original)' },
    202001: { id: 202001, name: 'Master of the Sands', description: 'Recover endurance and increase velocity when positioned toward the back mid-race. (Dirt)', isUnique: false, uniqueFor: '' },
    200332: { id: 200332, name: 'Corner Adept ○', description: 'Slightly increase velocity on a corner with skilled turning.', isUnique: false, uniqueFor: '' },
    200362: { id: 200362, name: 'Straightaway Adept', description: 'Slightly increase velocity on a straight.', isUnique: false, uniqueFor: '' },
    200462: { id: 200462, name: 'Ramp Up', description: 'Slightly increase velocity when passing another runner mid-race.', isUnique: false, uniqueFor: '' },
    200512: { id: 200512, name: 'Homestretch Haste', description: 'Slightly increase velocity in the last spurt.', isUnique: false, uniqueFor: '' },
    200542: { id: 200542, name: 'Fast-Paced', description: 'Slightly increase ability to go to the front mid-race. (Front Runner)', isUnique: false, uniqueFor: '' },
    200582: { id: 200582, name: 'Prepared to Pass', description: 'Slightly increase ability to break out of the pack on the final corner. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    200592: { id: 200592, name: 'Position Pilfer', description: 'Slightly increase velocity mid-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    200612: { id: 200612, name: 'Outer Swell', description: 'Slightly increase velocity when passing another runner on the outside on the final corner. (Late Surger)', isUnique: false, uniqueFor: '' },
    200632: { id: 200632, name: 'Masterful Gambit', description: 'Slightly move up in preparation to close the gap when positioned toward the back late-race. (End Closer)', isUnique: false, uniqueFor: '' },
    200672: { id: 200672, name: 'Gap Closer', description: 'Slightly increase spurting ability when positioned toward the back late-race. (Sprint)', isUnique: false, uniqueFor: '' },
    200682: { id: 200682, name: 'Productive Plan', description: 'Slightly widen the margin when positioned toward the front early-race. (Mile)', isUnique: false, uniqueFor: '' },
    200722: { id: 200722, name: 'Up-Tempo', description: 'Slightly increase positioning ability when positioned toward the front mid-race. (Medium)', isUnique: false, uniqueFor: '' },
    200732: { id: 200732, name: 'Steadfast', description: 'Slightly increase ability to fight back when passed by another runner on the final corner. (Medium)', isUnique: false, uniqueFor: '' },
    200752: { id: 200752, name: 'Inside Scoop', description: 'Slightly increase velocity when near the inner rail on the final corner. (Long)', isUnique: false, uniqueFor: '' },
    200961: { id: 200961, name: 'Sprint Straightaways ◎', description: 'Moderately increase velocity on a straight. (Sprint)', isUnique: false, uniqueFor: '' },
    200962: { id: 200962, name: 'Sprint Straightaways ○', description: 'Slightly increase velocity on a straight. (Sprint)', isUnique: false, uniqueFor: '' },
    200971: { id: 200971, name: 'Sprint Corners ◎', description: 'Moderately increase velocity on a corner. (Sprint)', isUnique: false, uniqueFor: '' },
    200972: { id: 200972, name: 'Sprint Corners ○', description: 'Slightly increase velocity on a corner. (Sprint)', isUnique: false, uniqueFor: '' },
    200982: { id: 200982, name: 'Huge Lead', description: 'Slightly increase ability to maintain the lead when leading by a large margin mid-race. (Sprint)', isUnique: false, uniqueFor: '' },
    201031: { id: 201031, name: 'Mile Straightaways ◎', description: 'Moderately increase velocity on a straight. (Mile)', isUnique: false, uniqueFor: '' },
    201032: { id: 201032, name: 'Mile Straightaways ○', description: 'Slightly increase velocity on a straight. (Mile)', isUnique: false, uniqueFor: '' },
    201041: { id: 201041, name: 'Mile Corners ◎', description: 'Moderately increase velocity on a corner. (Mile)', isUnique: false, uniqueFor: '' },
    201042: { id: 201042, name: 'Mile Corners ○', description: 'Slightly increase velocity on a corner. (Mile)', isUnique: false, uniqueFor: '' },
    201052: { id: 201052, name: 'Shifting Gears', description: 'Slightly increase passing ability when positioned toward the front mid-race. (Mile)', isUnique: false, uniqueFor: '' },
    201072: { id: 201072, name: 'Unyielding Spirit', description: 'Slightly increase passing ability. (Mile)', isUnique: false, uniqueFor: '' },
    201101: { id: 201101, name: 'Medium Straightaways ◎', description: 'Moderately increase velocity on a straight. (Medium)', isUnique: false, uniqueFor: '' },
    201102: { id: 201102, name: 'Medium Straightaways ○', description: 'Slightly increase velocity on a straight. (Medium)', isUnique: false, uniqueFor: '' },
    201111: { id: 201111, name: 'Medium Corners ◎', description: 'Moderately increase velocity on a corner. (Medium)', isUnique: false, uniqueFor: '' },
    201112: { id: 201112, name: 'Medium Corners ○', description: 'Slightly increase velocity on a corner. (Medium)', isUnique: false, uniqueFor: '' },
    201171: { id: 201171, name: 'Long Straightaways ◎', description: 'Moderately increase velocity on a straight. (Long)', isUnique: false, uniqueFor: '' },
    201172: { id: 201172, name: 'Long Straightaways ○', description: 'Slightly increase velocity on a straight. (Long)', isUnique: false, uniqueFor: '' },
    201181: { id: 201181, name: 'Long Corners ◎', description: 'Moderately increase velocity on a corner. (Long)', isUnique: false, uniqueFor: '' },
    201182: { id: 201182, name: 'Long Corners ○', description: 'Slightly increase velocity on a corner. (Long)', isUnique: false, uniqueFor: '' },
    201192: { id: 201192, name: 'Keeping the Lead', description: 'Slightly increase ability to maintain the lead when leading by a fair margin mid-race. (Long)', isUnique: false, uniqueFor: '' },
    201212: { id: 201212, name: 'Pressure', description: 'Slightly increase velocity when passing another runner late-race. (Long)', isUnique: false, uniqueFor: '' },
    201241: { id: 201241, name: 'Front Runner Straightaways ◎', description: 'Moderately increase velocity on a straight. (Front Runner)', isUnique: false, uniqueFor: '' },
    201242: { id: 201242, name: 'Front Runner Straightaways ○', description: 'Slightly increase velocity on a straight. (Front Runner)', isUnique: false, uniqueFor: '' },
    201251: { id: 201251, name: 'Front Runner Corners ◎', description: 'Moderately increase velocity on a corner. (Front Runner)', isUnique: false, uniqueFor: '' },
    201252: { id: 201252, name: 'Front Runner Corners ○', description: 'Slightly increase velocity on a corner. (Front Runner)', isUnique: false, uniqueFor: '' },
    201272: { id: 201272, name: 'Leader\'s Pride', description: 'Slightly increase ability to pass or challenge another runner early-race or mid-race. (Front Runner)', isUnique: false, uniqueFor: '' },
    201311: { id: 201311, name: 'Pace Chaser Straightaways ◎', description: 'Moderately increase velocity on a straight. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201312: { id: 201312, name: 'Pace Chaser Straightaways ○', description: 'Slightly increase velocity on a straight. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201321: { id: 201321, name: 'Pace Chaser Corners ◎', description: 'Moderately increase velocity on a corner. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201322: { id: 201322, name: 'Pace Chaser Corners ○', description: 'Slightly increase velocity on a corner. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201381: { id: 201381, name: 'Late Surger Straightaways ◎', description: 'Moderately increase velocity on a straight. (Late Surger)', isUnique: false, uniqueFor: '' },
    201382: { id: 201382, name: 'Late Surger Straightaways ○', description: 'Slightly increase velocity on a straight. (Late Surger)', isUnique: false, uniqueFor: '' },
    201391: { id: 201391, name: 'Late Surger Corners ◎', description: 'Moderately increase velocity on a corner. (Late Surger)', isUnique: false, uniqueFor: '' },
    201392: { id: 201392, name: 'Late Surger Corners ○', description: 'Slightly increase velocity on a corner. (Late Surger)', isUnique: false, uniqueFor: '' },
    201412: { id: 201412, name: '1,500,000 CC', description: 'Slightly increase velocity on an uphill. (Late Surger)', isUnique: false, uniqueFor: '' },
    201451: { id: 201451, name: 'End Closer Straightaways ◎', description: 'Moderately increase velocity on a straight. (End Closer)', isUnique: false, uniqueFor: '' },
    201452: { id: 201452, name: 'End Closer Straightaways ○', description: 'Slightly increase velocity on a straight. (End Closer)', isUnique: false, uniqueFor: '' },
    201461: { id: 201461, name: 'End Closer Corners ◎', description: 'Moderately increase velocity on a corner. (End Closer)', isUnique: false, uniqueFor: '' },
    201462: { id: 201462, name: 'End Closer Corners ○', description: 'Slightly increase velocity on a corner. (End Closer)', isUnique: false, uniqueFor: '' },
    201591: { id: 201591, name: 'Uma Stan', description: 'Slightly increase velocity when close to many runners.', isUnique: false, uniqueFor: '' },
    201611: { id: 201611, name: 'Tail Held High', description: 'Slightly increase velocity after activating many skills mid-race.', isUnique: false, uniqueFor: '' },
    201651: { id: 201651, name: 'Slipstream', description: 'Slightly decrease wind resistance when following directly behind another runner.', isUnique: false, uniqueFor: '' },
    201661: { id: 201661, name: 'Playtime\'s Over!', description: 'Slightly increase velocity when followed by another runner directly behind for a long time.', isUnique: false, uniqueFor: '' },
    201672: { id: 201672, name: 'Top Pick', description: 'Slightly increase velocity when engaged in a challenge mid-race. (Dirt)', isUnique: false, uniqueFor: '' },
    201702: { id: 201702, name: 'All I\'ve Got', description: 'Slightly increase velocity when well-positioned on a straight in the last spurt. (Medium)', isUnique: false, uniqueFor: '' },
    202012: { id: 202012, name: 'Feature Act', description: 'Slightly increase velocity when positioned toward the front upon approaching late-race. (Long)', isUnique: false, uniqueFor: '' },
    202022: { id: 202022, name: 'Early Start', description: 'Very slightly increase velocity for a medium duration when positioned toward the back mid-race. (End Closer)', isUnique: false, uniqueFor: '' },
    202032: { id: 202032, name: 'Risky Business', description: 'Moderately increase velocity in the second half of the race, but also greatly increase fatigue sometimes.', isUnique: false, uniqueFor: '' },
    202042: { id: 202042, name: 'Light as a Feather', description: 'Slightly increase velocity when positioned toward the front upon approaching late-race. (Sprint)', isUnique: false, uniqueFor: '' },
    202092: { id: 202092, name: 'Fighting Spirit', description: 'When engaged in a challenge midpack mid-race, very slightly recover endurance and slightly increase velocity. (Medium)', isUnique: false, uniqueFor: '' },
    202102: { id: 202102, name: 'Eager', description: 'When positioned toward the back mid-race, slightly increase velocity. (Medium)', isUnique: false, uniqueFor: '' },
    202112: { id: 202112, name: 'Pumped', description: 'When positioned toward the back on the final corner, slightly increase velocity. (Mile)', isUnique: false, uniqueFor: '' },
    202122: { id: 202122, name: 'Fearless', description: 'When positioned in the midpack during the second half of the race, slightly increase velocity and very minimally increase acceleration. (Late Surger)', isUnique: false, uniqueFor: '' },
    202132: { id: 202132, name: 'With All My Soul', description: 'When positioned toward the front mid-race, slightly increase velocity and minimally decrease the velocity of runners behind the user. (Medium)', isUnique: false, uniqueFor: '' },
    202152: { id: 202152, name: 'Full Throttle', description: 'Greatly consume endurance mid-race and moderately increase velocity. (Late Surger)', isUnique: false, uniqueFor: '' },
    202172: { id: 202172, name: 'Downhill Speedster', description: 'Slightly increase velocity on downhills.', isUnique: false, uniqueFor: '' },
    200331: { id: 200331, name: 'Professor of Curvature', description: 'Increase velocity on a corner with skilled turning.', isUnique: false, uniqueFor: '' },
    200361: { id: 200361, name: 'Beeline Burst', description: 'Increase velocity on a straight.', isUnique: false, uniqueFor: '' },
    200461: { id: 200461, name: 'It\'s On!', description: 'Increase velocity when passing another runner mid-race.', isUnique: false, uniqueFor: '' },
    200511: { id: 200511, name: 'In Body and Mind', description: 'Increase velocity in the last spurt.', isUnique: false, uniqueFor: '' },
    200541: { id: 200541, name: 'Escape Artist', description: 'Increase ability to go to the front mid-race. (Front Runner)', isUnique: false, uniqueFor: '' },
    200581: { id: 200581, name: 'Speed Star', description: 'Increase ability to break out of the pack on the final corner. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    200591: { id: 200591, name: 'Fast & Furious', description: 'Increase velocity mid-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    200611: { id: 200611, name: 'Rising Dragon', description: 'Increase velocity when passing another runner on the outside on the final corner. (Late Surger)', isUnique: false, uniqueFor: '' },
    200631: { id: 200631, name: 'Sturm und Drang', description: 'Move up in preparation to close the gap when positioned toward the back late-race. (End Closer)', isUnique: false, uniqueFor: '' },
    200671: { id: 200671, name: 'Blinding Flash', description: 'Increase spurting ability when positioned toward the back late-race. (Sprint)', isUnique: false, uniqueFor: '' },
    200681: { id: 200681, name: 'Mile Maven', description: 'Widen the margin when positioned toward the front early-race. (Mile)', isUnique: false, uniqueFor: '' },
    200721: { id: 200721, name: 'Killer Tunes', description: 'Increase positioning ability when positioned toward the front mid-race. (Medium)', isUnique: false, uniqueFor: '' },
    200731: { id: 200731, name: 'Unyielding', description: 'Increase ability to fight back when passed by another runner on the final corner. (Medium)', isUnique: false, uniqueFor: '' },
    200751: { id: 200751, name: 'Innate Experience', description: 'Increase velocity when near the inner rail on the final corner. (Long)', isUnique: false, uniqueFor: '' },
    200981: { id: 200981, name: 'Staggering Lead', description: 'Increase ability to maintain the lead when leading by a large margin mid-race. (Sprint)', isUnique: false, uniqueFor: '' },
    201051: { id: 201051, name: 'Changing Gears', description: 'Increase passing ability when positioned toward the front mid-race. (Mile)', isUnique: false, uniqueFor: '' },
    201071: { id: 201071, name: 'Big-Sisterly', description: 'Increase passing ability. (Mile)', isUnique: false, uniqueFor: '' },
    201191: { id: 201191, name: 'Vanguard Spirit', description: 'Increase ability to maintain the lead when leading by a fair margin mid-race. (Long)', isUnique: false, uniqueFor: '' },
    201211: { id: 201211, name: 'Overwhelming Pressure', description: 'Increase velocity when passing another runner late-race. (Long)', isUnique: false, uniqueFor: '' },
    201411: { id: 201411, name: '15,000,000 CC', description: 'Increase velocity on an uphill. (Late Surger)', isUnique: false, uniqueFor: '' },
    201671: { id: 201671, name: 'Trending in the Charts!', description: 'Increase velocity when engaged in a challenge mid-race. (Dirt)', isUnique: false, uniqueFor: '' },
    201592: { id: 201592, name: 'Superstan', description: 'Increase velocity when close to many runners.', isUnique: false, uniqueFor: '' },
    201701: { id: 201701, name: 'Come What May', description: 'Increase velocity when well-positioned on a straight in the last spurt. (Medium)', isUnique: false, uniqueFor: '' },
    201612: { id: 201612, name: 'Tail Nine', description: 'Increase velocity after activating many skills mid-race.', isUnique: false, uniqueFor: '' },
    300061: { id: 300061, name: 'Dream Run', description: 'Increase velocity on the final straight due to a strong desire to cross the finish line carrying everyone\'s hopes and dreams.', isUnique: false, uniqueFor: '' },
    202011: { id: 202011, name: 'Headliner', description: 'Increase velocity when positioned toward the front upon approaching late-race. (Long)', isUnique: false, uniqueFor: '' },
    202021: { id: 202021, name: 'Daring Strike', description: 'Moderately increase velocity for a medium duration when positioned toward the back mid-race. (End Closer)', isUnique: false, uniqueFor: '' },
    202031: { id: 202031, name: 'Nothing Ventured', description: 'Greatly increase velocity in the second half of the race, but also greatly increase fatigue sometimes.', isUnique: false, uniqueFor: '' },
    201103: { id: 201103, name: 'Flash Forward', description: 'Increase velocity on a straight. (Medium)', isUnique: false, uniqueFor: '' },
    202041: { id: 202041, name: 'In High Spirits', description: 'Increase velocity when positioned toward the front upon approaching late-race. (Sprint)', isUnique: false, uniqueFor: '' },
    201173: { id: 201173, name: 'Blast Forward', description: 'Increase velocity on a straight. (Long)', isUnique: false, uniqueFor: '' },
    201271: { id: 201271, name: 'Top Runner', description: 'Increase ability to pass or challenge another runner early-race or mid-race. (Front Runner)', isUnique: false, uniqueFor: '' },
    202091: { id: 202091, name: 'Burning Soul', description: 'When engaged in a challenge midpack mid-race, moderately recover endurance and moderately increase velocity. (Medium)', isUnique: false, uniqueFor: '' },
    202101: { id: 202101, name: 'Elated', description: 'When positioned toward the back mid-race, increase velocity. (Medium)', isUnique: false, uniqueFor: '' },
    202111: { id: 202111, name: 'Full of Vigor', description: 'When positioned toward the back on the final corner, increase velocity. (Mile)', isUnique: false, uniqueFor: '' },
    202121: { id: 202121, name: 'Dauntless', description: 'When positioned in the midpack during the second half of the race, increase velocity and very slightly increase acceleration. (Late Surger)', isUnique: false, uniqueFor: '' },
    202131: { id: 202131, name: 'Wild Wind', description: 'When positioned toward the front mid-race, increase velocity and slightly decrease the velocity of runners behind the user. (Medium)', isUnique: false, uniqueFor: '' },
    201662: { id: 201662, name: 'See Ya Later!', description: 'Increase velocity when followed by another runner directly behind for a long time.', isUnique: false, uniqueFor: '' },
    202151: { id: 202151, name: 'Keep Going!', description: 'Greatly consume endurance mid-race and greatly increase velocity. (Late Surger)', isUnique: false, uniqueFor: '' },
    201453: { id: 201453, name: 'Moonlit Flash', description: 'Increase velocity on straights. (End Closer)', isUnique: false, uniqueFor: '' },
    201113: { id: 201113, name: 'Refraction Arc', description: 'Increase velocity on corners. (Medium)', isUnique: false, uniqueFor: '' },
    110031: { id: 110031, name: 'Certain Victory', description: 'Greatly increase velocity with an indomitable fighting spirit on the final straight after being on the heels of another runner toward the front on the final corner or later.', isUnique: true, uniqueFor: 'Tokai Teio (Anime Collab)' },
    110131: { id: 110131, name: 'Legacy of the Strong', description: 'Increase velocity continuously when pressured by another runner and running out of energy toward the front on the final corner or later.', isUnique: true, uniqueFor: 'Mejiro McQueen (Anime Collab)' },
    10071: { id: 10071, name: 'Warning Shot!', description: 'Slightly increase velocity with a long spurt starting halfway through the race.', isUnique: true, uniqueFor: 'Gold Ship (Original)' },
    10081: { id: 10081, name: 'Xceleration', description: 'Become stronger at challenging rivals and moderately increase velocity when positioned toward the front with 200m or less remaining.', isUnique: true, uniqueFor: 'Vodka (Original)' },
    10091: { id: 10091, name: 'Red Ace', description: 'Slightly swell with the determination to be number one when positioned toward the front in the second half of the race.', isUnique: true, uniqueFor: 'Daiwa Scarlet (Original)' },
    10111: { id: 10111, name: 'Focused Mind', description: 'Moderately increase velocity with a strong turn of foot when passing another runner toward the back on the final straight.', isUnique: true, uniqueFor: 'Grass Wonder (Original)' },
    10141: { id: 10141, name: 'Corazón ☆ Ardiente', description: 'Slightly hang on to the advantage when positioned toward the front with energy to spare on the final straight.', isUnique: true, uniqueFor: 'El Condor Pasa (Original)' },
    10181: { id: 10181, name: 'Empress\'s Pride', description: 'Moderately increase velocity with the stride of an empress when passing another runner from midpack or further back on the final corner.', isUnique: true, uniqueFor: 'Air Groove (Original)' },
    10241: { id: 10241, name: '1st Place Kiss☆', description: 'Slightly increase ability to break out of the pack on the straight after engaging in a challenge toward the front on the final corner or later.', isUnique: true, uniqueFor: 'Mayano Top Gun (Original)' },
    10351: { id: 10351, name: 'V Is for Victory!', description: 'Moderately increase velocity with winning ambition when positioned toward the front on the final straight after engaging in a challenge on the final corner or later.', isUnique: true, uniqueFor: 'Winning Ticket (Original)' },
    10411: { id: 10411, name: 'Class Rep + Speed = Bakushin', description: 'Moderately increase velocity with BAKUSHIN power when engaged in a challenge toward the front in the second half of the race.', isUnique: true, uniqueFor: 'Sakura Bakushin O (Original)' },
    10561: { id: 10561, name: 'Luck Be with Me!', description: 'Moderately clear a path forward with the power of divination when the way ahead is jammed late-race.', isUnique: true, uniqueFor: 'Matikanefukukitaru (Original)' },
    10601: { id: 10601, name: 'I Can Win Sometimes, Right?', description: 'Moderately increase velocity with an arousal of fighting spirit when positioned 3rd and about to lose late-race.', isUnique: true, uniqueFor: 'Nice Nature (Original)' },
    10611: { id: 10611, name: 'Call Me King', description: 'Increase velocity in a true display of skill with 200m remaining after racing calmly.', isUnique: true, uniqueFor: 'King Halo (Original)' },
    100011: { id: 100011, name: 'Shooting Star', description: 'Ride the momentum to increase velocity and very slightly increase acceleration after passing another runner toward the front late-race.', isUnique: true, uniqueFor: 'Special Week (Original)' },
    100021: { id: 100021, name: 'The View from the Lead Is Mine!', description: 'Increase velocity by drawing on all remaining strength when in the lead by a fair margin in the second half of the race.', isUnique: true, uniqueFor: 'Silence Suzuka (Original)' },
    100031: { id: 100031, name: 'Sky-High Teio Step', description: 'Greatly increase velocity with flashy footwork when closing the gap to runners ahead on the final straight.', isUnique: true, uniqueFor: 'Tokai Teio (Original)' },
    100061: { id: 100061, name: 'Triumphant Pulse', description: 'Greatly increase ability to break out of the pack by opening up a path when positioned toward the front with 200m remaining.', isUnique: true, uniqueFor: 'Oguri Cap (Original)' },
    100071: { id: 100071, name: 'Anchors Aweigh!', description: 'Moderately increase velocity steadily with a long spurt starting halfway through the race.', isUnique: true, uniqueFor: 'Gold Ship (Original)' },
    100081: { id: 100081, name: 'Cut and Drive!', description: 'Become stronger at challenging rivals and increase velocity when positioned toward the front with 200m or less remaining.', isUnique: true, uniqueFor: 'Vodka (Original)' },
    100091: { id: 100091, name: 'Resplendent Red Ace', description: 'Swell with the determination to be number one when positioned toward the front in the second half of the race.', isUnique: true, uniqueFor: 'Daiwa Scarlet (Original)' },
    100111: { id: 100111, name: 'Where There\'s a Will, There\'s a Way', description: 'Increase velocity with a strong turn of foot when passing another runner toward the back on the final straight.', isUnique: true, uniqueFor: 'Grass Wonder (Original)' },
    100131: { id: 100131, name: 'The Duty of Dignity Calls', description: 'Increase velocity with the determination to not be overtaken when positioned toward the front on the final corner.', isUnique: true, uniqueFor: 'Mejiro McQueen (Original)' },
    100141: { id: 100141, name: 'Victoria por plancha ☆', description: 'Hang onto the advantage when positioned toward the front with energy to spare on the final straight.', isUnique: true, uniqueFor: 'El Condor Pasa (Original)' },
    100151: { id: 100151, name: 'This Dance Is for Vittoria!', description: 'Increase velocity with royal brilliance when positioned toward the front and close to the runner ahead or behind on the final corner or later.', isUnique: true, uniqueFor: 'TM Opera O (Original)' },
    100171: { id: 100171, name: 'Behold Thine Emperor\'s Divine Might', description: 'Greatly increase velocity on the final straight after passing another runner 3 times late-race.', isUnique: true, uniqueFor: 'Symboli Rudolf (Original)' },
    100181: { id: 100181, name: 'Blazing Pride', description: 'Increase velocity with the stride of an empress when passing another runner from midpack or further back on the final corner.', isUnique: true, uniqueFor: 'Air Groove (Original)' },
    100231: { id: 100231, name: '∴win Q.E.D.', description: 'Increase velocity by deriving the winning equation when passing another runner toward the front on the final corner or later.', isUnique: true, uniqueFor: 'Biwa Hayahide (Original)' },
    100241: { id: 100241, name: 'Flashy☆Landing', description: 'Increase ability to break out of the pack on the straight after engaging in a challenge toward the front on the final corner or later.', isUnique: true, uniqueFor: 'Mayano Top Gun (Original)' },
    100261: { id: 100261, name: 'G00 1st. F∞;', description: 'Increase velocity when positioned toward the front after making it to the final straight without faltering.', isUnique: true, uniqueFor: 'Mihono Bourbon (Original)' },
    100301: { id: 100301, name: 'Blue Rose Closer', description: 'Increase velocity with strong willpower on the final straight after passing another runner in the front part of the pack on the final corner or later.', isUnique: true, uniqueFor: 'Rice Shower (Original)' },
    100351: { id: 100351, name: 'Our Ticket to Win!', description: 'Increase velocity with winning ambition when positioned toward the front on the final straight after engaging in a challenge on the final corner or later.', isUnique: true, uniqueFor: 'Winning Ticket (Original)' },
    100411: { id: 100411, name: 'Genius x Bakushin = Victory', description: 'Increase velocity with BAKUSHIN power when engaged in a challenge toward the front in the second half of the race.', isUnique: true, uniqueFor: 'Sakura Bakushin O (Original)' },
    100561: { id: 100561, name: 'I See Victory in My Future!', description: 'Clear a path forward with the power of divination when the way ahead is jammed late-race.', isUnique: true, uniqueFor: 'Matikanefukukitaru (Original)' },
    100601: { id: 100601, name: 'Just a Little Farther!', description: 'Increase velocity with flaring fighting spirit when positioned 3rd and about to lose late-race.', isUnique: true, uniqueFor: 'Nice Nature (Original)' },
    100611: { id: 100611, name: 'Prideful King', description: 'Greatly increase velocity in a true display of skill with 200m remaining after racing calmly.', isUnique: true, uniqueFor: 'King Halo (Original)' },
    100381: { id: 100381, name: '#LookatCurren', description: 'Gain momentum and begin to advance when passing another runner while well-positioned around halfway through the race.', isUnique: true, uniqueFor: 'Curren Chan (Original)' },
    100501: { id: 100501, name: 'Nemesis', description: 'Increase velocity with smoldering ambition when moving up from midpack on the final corner or later.', isUnique: true, uniqueFor: 'Narita Taishin (Original)' },
    100461: { id: 100461, name: 'SPARKLY☆STARDOM', description: 'Become empowered to keep the spotlight when positioned toward the front and close to the runner behind on a straight mid-race.', isUnique: true, uniqueFor: 'Smart Falcon (Original)' },
    100161: { id: 100161, name: 'Shadow Break', description: 'Increase velocity with beastly strength when passing another runner on the outside on the final corner or later. If the skill user engaged in a challenge mid-race, greatly increase velocity instead.', isUnique: true, uniqueFor: 'Narita Brian (Original)' },
    110181: { id: 110181, name: 'Eternal Moments', description: 'Increase velocity when starting to make a move from a position toward the front mid-race.', isUnique: true, uniqueFor: 'Air Groove (Wedding)' },
    110241: { id: 110241, name: 'Flowery☆Maneuver', description: 'Increase velocity when passing another runner toward the front on the final corner. If passing toward the back, increase acceleration instead.', isUnique: true, uniqueFor: 'Mayano Top Gun (Wedding)' },
    100121: { id: 100121, name: 'You and Me! One-on-One!', description: 'Increase velocity on the final straight after passing another runner on the outside toward the back on the final corner or later.', isUnique: true, uniqueFor: 'Hishi Amazon (Original)' },
    100051: { id: 100051, name: 'Lights of Vaudeville', description: 'Greatly increase velocity with a dazzling display when just breaking out of the pack toward the front on the final straight.', isUnique: true, uniqueFor: 'Fuji Kiseki (Original)' },
    100401: { id: 100401, name: 'KEEP IT REAL.', description: 'Moderately increase acceleration steadily with a wink when starting to make a move from midpack in the second half of the race.', isUnique: true, uniqueFor: 'Gold City (Original)' },
    110041: { id: 110041, name: 'A Kiss for Courage', description: 'Increase velocity enthusiastically when positioned toward the front in the second half of the race after recovering endurance with a skill.', isUnique: true, uniqueFor: 'Maruzensky (Summer)' },
    100581: { id: 100581, name: 'I Never Goof Up!', description: 'Aim for the front with unwavering determination when passing another runner from midpack or further back on a corner late-race.', isUnique: true, uniqueFor: 'Meisho Doto (Original)' },
    100371: { id: 100371, name: 'Schwarzes Schwert', description: 'Increase velocity in a dash for the lead after running calmly and according to plan up until the final straight.', isUnique: true, uniqueFor: 'Eishin Flash (Original)' },
    110561: { id: 110561, name: 'Bountiful Harvest', description: 'Increase velocity with a surge of great fortune when pressured by another runner toward the back in the second half of the race.', isUnique: true, uniqueFor: 'Matikanefukukitaru (Full Armor)' },
    100281: { id: 100281, name: 'YUMMY☆SPEED!', description: 'Kick forward hard with renewed vigor when starting to get tired while well-positioned halfway through the race.', isUnique: true, uniqueFor: 'Hishi Akebono (Original)' },
    100191: { id: 100191, name: 'OMG! (ﾟ∀ﾟ) The Final Sprint! ☆', description: 'Increase velocity and navigation with the pure euphoria of being within breathing distance of precious waifus after passing another runner 2 times late-race.', isUnique: true, uniqueFor: 'Agnes Digital (Original)' },
    110451: { id: 110451, name: 'Give Mummy a Hug ♡', description: 'Increase ability to break out of the pack when well-positioned and close to the runner ahead on the final straight.', isUnique: true, uniqueFor: 'Super Creek (Halloween)' },
    100391: { id: 100391, name: 'A Princess Must Seize Victory!', description: 'Increase velocity with pretty princess power when engaged in a challenge on the final straight.', isUnique: true, uniqueFor: 'Kawakami Princess (Original)' },
    100251: { id: 100251, name: 'Chasing After You', description: 'Chase after an unseen friend when in midpack in the second half of the race, moderately increasing velocity steadily and very slightly intimidating runners ahead.', isUnique: true, uniqueFor: 'Manhattan Cafe (Original)' },
    110171: { id: 110171, name: 'Arrows Whistle, Shadows Disperse', description: 'Increase velocity with a blazing spirit when pressured by another runner in the front part of the pack on the final corner or later.', isUnique: true, uniqueFor: 'Symboli Rudolf (Festival)' },
    110401: { id: 110401, name: 'Dancing in the Leaves', description: 'Increase ability to break out of the pack when engaged in a challenge in midpack on the final corner.', isUnique: true, uniqueFor: 'Gold City (Festival)' },
    100481: { id: 100481, name: 'Pop & Polish', description: 'Get hyped and increase velocity when pressured by or passing another runner while well-positioned on the final straight.', isUnique: true, uniqueFor: 'Tosen Jordan (Original)' },
    110061: { id: 110061, name: 'Festive Miracle', description: 'Control breathing and kick forward hard toward victory in the second half of the race after recovering endurance with skills at least 3 times.', isUnique: true, uniqueFor: 'Oguri Cap (Christmas)' },
    110231: { id: 110231, name: 'Presents from X', description: 'Increase velocity by deriving a path to victory mid-race after staying well-positioned from the start of the race up until the second half.', isUnique: true, uniqueFor: 'Biwa Hayahide (Christmas)' },
    100221: { id: 100221, name: 'Fairy Tale', description: 'Increase velocity with the excitement of running when engaged in a challenge while well-positioned in the second half of the race.', isUnique: true, uniqueFor: 'Fine Motion (Original)' },
    100211: { id: 100211, name: 'White Lightning Comin\' Through!', description: 'Bolt down the track like lightning when well-positioned or aiming for the front from midpack on a straight in the second half of the race.', isUnique: true, uniqueFor: 'Tamamo Cross (Original)' },
    110151: { id: 110151, name: 'Barcarole of Blessings', description: 'Increase velocity for a moderate duration when in the front part of the pack with 400m remaining. If at least 7 skills have been activated, greatly increase velocity for a moderate duration instead.', isUnique: true, uniqueFor: 'TM Opera O (New Year)' },
    110521: { id: 110521, name: '114th Time\'s the Charm', description: 'Give max effort when far from the lead on the final corner, moderately increasing velocity steadily for a duration proportional to distance from the lead.', isUnique: true, uniqueFor: 'Haru Urara (New Year)' },
    100691: { id: 100691, name: 'Ambition to Surpass the Sakura', description: 'Increase velocity with blossoming ambition when well-positioned and close to the runner ahead with 300m or less remaining.', isUnique: true, uniqueFor: 'Sakura Chiyono O (Original)' },
    100711: { id: 100711, name: 'A Lifelong Dream, A Moment\'s Flight', description: 'Seize the moment when close to the runner behind on the final straight, slightly consuming endurance to greatly increase velocity for a moderate duration.', isUnique: true, uniqueFor: 'Mejiro Ardan (Original)' },
    110261: { id: 110261, name: 'Operation Cacao', description: 'Take a slight breather and increase velocity when in the front part of the pack and detecting another runner coming from behind on a corner mid-race.', isUnique: true, uniqueFor: 'Mihono Bourbon (Valentine)' },
    110371: { id: 110371, name: 'Guten Appetit ♪', description: 'Increase velocity continuously with a patissiere\'s pride on the final straight after passing another runner 3 times on the final corner or later.', isUnique: true, uniqueFor: 'Eishin Flash (Valentine)' },
    100331: { id: 100331, name: 'Shooting Star of Dioskouroi', description: 'Increase velocity with guidance from the stars when far from the lead on the final straight. If positioned around the very back, greatly increase velocity instead.', isUnique: true, uniqueFor: 'Admire Vega (Original)' },
    100681: { id: 100681, name: 'Victory Cheer!', description: 'Moderately increase velocity when positioned toward the front on the third corner in the second half of the race. Or, kick forward hard when toward the front on the backstretch late-race.', isUnique: true, uniqueFor: 'Kitasan Black (Original)' },
    100671: { id: 100671, name: 'Eternal Encompassing Shine', description: 'If well-positioned at the start of the final straight, her strong willpower to win increases velocity. If positioned near the front, greatly increase velocity instead.', isUnique: true, uniqueFor: 'Satono Diamond (Original)' },
    100741: { id: 100741, name: 'Lovely Spring Breeze', description: 'From the midpack in the second half of the race, slightly increase velocity steadily for a duration based on remaining endurance.', isUnique: true, uniqueFor: 'Mejiro Bright (Original)' },
    110051: { id: 110051, name: 'Ravissant', description: 'When passing another racer at the front part of the pack on the final corner or later, perform a dazzling display that greatly increases velocity for a moderate duration.', isUnique: true, uniqueFor: 'Fuji Kiseki (Ballroom)' },
    110201: { id: 110201, name: 'Break It Down!', description: 'If positioned toward the front on a straight late-race, increase velocity with high spirits. If the straight is on the backstretch, also increase acceleration very slightly.', isUnique: true, uniqueFor: 'Seiun Sky (Ballroom)' },
    100721: { id: 100721, name: 'Peerless Dance of Flowering Flames', description: 'If the user passes another runner on the final corner or later, increase velocity with fiery fighting spirit when in the front part of the pack with 300m or less remaining.', isUnique: true, uniqueFor: 'Yaeno Muteki (Original)' },
    110601: { id: 110601, name: 'Go☆Go☆Goal!', description: 'If the user passes another runner on the final corner or later, increase velocity from the midpack onward on the final straight. If the user isn\'t one of the top favorites, muster resolve to keep steadily increasing velocity.', isUnique: true, uniqueFor: 'Nice Nature (Cheerleader)' },
    100311: { id: 100311, name: 'All Charged! It\'s Go Time!', description: 'Moderately increase velocity when positioned toward the front with about 300m remaining. If coming out of an uphill, greatly increase velocity instead.', isUnique: true, uniqueFor: 'Ines Fujin (Original)' },
    110221: { id: 110221, name: 'Best Day Ever', description: 'If well-positioned late-race on the final corner or later, increase velocity. If there\'s a large distance left to the finish, also increase acceleration very slightly with perfect form.', isUnique: true, uniqueFor: 'Fine Motion (Wedding)' },
    110381: { id: 110381, name: 'One True Color', description: 'If positioned toward the front with 350m or less remaining and there is another Umamusume close behind, the determination to stay ahead makes it easier to break out of the pack.', isUnique: true, uniqueFor: 'Curren Chan (Wedding)' },
    100341: { id: 100341, name: 'Now We\'re Cruisin\'!', description: 'When competing for the lead if positioned in the midpack or further for the first half of the race, show off some Edo spirit and greatly increase velocity.', isUnique: true, uniqueFor: 'Inari One (Original)' },
    100441: { id: 100441, name: 'Victory belongs to me—Strelitzia! ☆', description: 'If positioned toward the back and racing calmly until the start of the final corner, when there are 300m remaining, cast a magic spell to increase velocity continuously.', isUnique: true, uniqueFor: 'Sweep Tosho (Original)' },
    110101: { id: 110101, name: 'Joyful Voyage!', description: 'If positioned toward the front with 200m remaining, increase velocity. Then, if also positioned near the leading Umamusume, gather strength to move slightly forward.', isUnique: true, uniqueFor: 'Taiki Shuttle (Camping)' },
    110591: { id: 110591, name: 'Wherever This Wonder Leads', description: 'If positioned midpack on a downhill just before late-race and there\'s a large distance left to the finish, enjoy the race to the fullest, increasing velocity.', isUnique: true, uniqueFor: 'Mejiro Dober (Camping)' },
    100361: { id: 100361, name: 'trigger:BEAT', description: 'When near the inner rail midpack on the final corner or later, calculate the path to victory, increasing velocity and ability to navigate smoothly on the final straight.', isUnique: true, uniqueFor: 'Air Shakur (Original)' },
    120011: { id: 120011, name: 'Dreams Donned with Pride!', description: 'If the user activates another skill on the final corner late-race, take the crowd\'s cheers to heart and moderately increase velocity. If racing at Nakayama Racecourse, greatly increase velocity instead.', isUnique: true, uniqueFor: 'Special Week (Commander)' },
    300131: { id: 300131, name: 'Ruler of Japan', description: 'I\'ll tackle this with everything I\'ve got!', isUnique: false, uniqueFor: '' },
    300141: { id: 300141, name: 'Indomitable', description: 'I\'ll rise up to the challenge!', isUnique: false, uniqueFor: '' },
    200333: { id: 200333, name: 'Corner Adept ×', description: 'Moderately decrease velocity on a corner with clumsy turning.', isUnique: false, uniqueFor: '' },
    200411: { id: 200411, name: 'Defeatist', description: 'Moderately increase urge to give up when positioned around the very back on the final straight.', isUnique: false, uniqueFor: '' },
    200421: { id: 200421, name: 'Reckless', description: 'Moderately increase carelessness when in the lead with around 200m remaining.', isUnique: false, uniqueFor: '' },
    300051: { id: 300051, name: 'Blatant Fear', description: 'Greatly decrease velocity on a corner in the second half of the race due to Trainer\'s obvious anxiety.', isUnique: false, uniqueFor: '' },
    200342: { id: 200342, name: 'Corner Acceleration ○', description: 'Slightly increase acceleration on a corner with masterful turning.', isUnique: false, uniqueFor: '' },
    200372: { id: 200372, name: 'Straightaway Acceleration', description: 'Slightly increase acceleration on a straight.', isUnique: false, uniqueFor: '' },
    200492: { id: 200492, name: 'Nimble Navigator', description: 'Slightly increase maneuverability when the way ahead is blocked in the last spurt.', isUnique: false, uniqueFor: '' },
    200532: { id: 200532, name: 'Early Lead', description: 'Slightly increase ability to go to the front early-race. (Front Runner)', isUnique: false, uniqueFor: '' },
    200552: { id: 200552, name: 'Final Push', description: 'Slightly increase ability to keep the lead on the final corner. (Front Runner)', isUnique: false, uniqueFor: '' },
    200602: { id: 200602, name: 'Slick Surge', description: 'Slightly increase acceleration late-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    200642: { id: 200642, name: 'Straightaway Spurt', description: 'Slightly increase acceleration on a straight in the last spurt. (End Closer)', isUnique: false, uniqueFor: '' },
    200652: { id: 200652, name: 'Sprinting Gear', description: 'Slightly increase acceleration on a straight. (Sprint)', isUnique: false, uniqueFor: '' },
    200702: { id: 200702, name: 'Updrafters', description: 'Slightly increase passing ability when positioned toward the back late-race. (Mile)', isUnique: false, uniqueFor: '' },
    200992: { id: 200992, name: 'Countermeasure', description: 'Slightly increase passing ability when positioned toward the front upon approaching late-race. (Sprint)', isUnique: false, uniqueFor: '' },
    201062: { id: 201062, name: 'Acceleration', description: 'Slightly increase acceleration when passing another runner mid-race. (Mile)', isUnique: false, uniqueFor: '' },
    201292: { id: 201292, name: 'Second Wind', description: 'Slightly increase acceleration when not in the lead mid-race. (Front Runner)', isUnique: false, uniqueFor: '' },
    201332: { id: 201332, name: 'Shrewd Step', description: 'Slightly increase ability to navigate smoothly. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201342: { id: 201342, name: 'Straight Descent', description: 'Slightly improve running on a downhill. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201362: { id: 201362, name: 'Tactical Tweak', description: 'Slightly increase acceleration when positioned toward the back mid-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201402: { id: 201402, name: 'Fighter', description: 'Slightly increase acceleration for a medium duration when trying to pass another runner. (Late Surger)', isUnique: false, uniqueFor: '' },
    201581: { id: 201581, name: 'Highlander', description: 'Slightly improve running on an uphill.', isUnique: false, uniqueFor: '' },
    201601: { id: 201601, name: 'Groundwork', description: 'Slightly increase acceleration after activating many skills early-race.', isUnique: false, uniqueFor: '' },
    201902: { id: 201902, name: 'Head-On', description: 'Slightly increase acceleration when positioned toward the front late-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    202082: { id: 202082, name: 'Take the Chance', description: 'If positioned toward the back late-race, slightly increase acceleration. (Medium)', isUnique: false, uniqueFor: '' },
    200341: { id: 200341, name: 'Corner Connoisseur', description: 'Increase acceleration on a corner with masterful turning.', isUnique: false, uniqueFor: '' },
    200371: { id: 200371, name: 'Rushing Gale!', description: 'Increase acceleration on a straight.', isUnique: false, uniqueFor: '' },
    200491: { id: 200491, name: 'No Stopping Me!', description: 'Increase maneuverability when the way ahead is blocked in the last spurt.', isUnique: false, uniqueFor: '' },
    200531: { id: 200531, name: 'Taking the Lead', description: 'Increase ability to go to the front early-race. (Front Runner)', isUnique: false, uniqueFor: '' },
    200551: { id: 200551, name: 'Unrestrained', description: 'Increase ability to keep the lead on the final corner. (Front Runner)', isUnique: false, uniqueFor: '' },
    200601: { id: 200601, name: 'On Your Left!', description: 'Increase acceleration late-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    200641: { id: 200641, name: 'Encroaching Shadow', description: 'Increase acceleration on a straight in the last spurt. (End Closer)', isUnique: false, uniqueFor: '' },
    200651: { id: 200651, name: 'Turbo Sprint', description: 'Increase acceleration on a straight. (Sprint)', isUnique: false, uniqueFor: '' },
    200701: { id: 200701, name: 'Furious Feat', description: 'Increase passing ability when positioned toward the back late-race. (Mile)', isUnique: false, uniqueFor: '' },
    200991: { id: 200991, name: 'Plan X', description: 'Increase passing ability when positioned toward the front upon approaching late-race. (Sprint)', isUnique: false, uniqueFor: '' },
    201061: { id: 201061, name: 'Step on the Gas!', description: 'Increase acceleration when passing another runner mid-race. (Mile)', isUnique: false, uniqueFor: '' },
    201291: { id: 201291, name: 'Reignition', description: 'Increase acceleration when not in the lead mid-race. (Front Runner)', isUnique: false, uniqueFor: '' },
    201331: { id: 201331, name: 'Technician', description: 'Moderately increase ability to navigate smoothly. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201341: { id: 201341, name: 'Determined Descent', description: 'Moderately improve running on a downhill. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201361: { id: 201361, name: 'Shatterproof', description: 'Moderately increase acceleration when positioned toward the back mid-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201401: { id: 201401, name: 'Hard Worker', description: 'Moderately increase acceleration for a medium duration when trying to pass another runner. (Late Surger)', isUnique: false, uniqueFor: '' },
    202081: { id: 202081, name: 'From the Brink', description: 'If positioned toward the back late-race, increase acceleration. (Medium)', isUnique: false, uniqueFor: '' },
    201901: { id: 201901, name: 'Neck and Neck', description: 'Increase acceleration when positioned toward the front late-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    10271: { id: 10271, name: 'Feel the Burn!', description: 'Moderately increase acceleration in an attempt to move up on a corner late-race.', isUnique: true, uniqueFor: 'Mejiro Ryan (Original)' },
    100041: { id: 100041, name: 'Red Shift/LP1211-M', description: 'Increase acceleration by shifting gears when positioned toward the front on the final corner or later.', isUnique: true, uniqueFor: 'Maruzensky (Original)' },
    100101: { id: 100101, name: 'Shooting for Victory!', description: 'Increase acceleration with a pow, a wow, and a bang when well-positioned upon approaching the final straight.', isUnique: true, uniqueFor: 'Taiki Shuttle (Original)' },
    100271: { id: 100271, name: 'Let\'s Pump Some Iron!', description: 'Increase acceleration in an attempt to move up on a corner late-race.', isUnique: true, uniqueFor: 'Mejiro Ryan (Original)' },
    100201: { id: 100201, name: 'Angling and Scheming', description: 'Increase acceleration at an opportune moment when in the lead on a corner late-race.', isUnique: true, uniqueFor: 'Seiun Sky (Original)' },
    110141: { id: 110141, name: 'Condor\'s Fury', description: 'Increase acceleration with blazing passion when aiming for the front from midpack on the final corner.', isUnique: true, uniqueFor: 'El Condor Pasa (Fantasy)' },
    100591: { id: 100591, name: 'Moving Past, and Beyond', description: 'Having run the race calmly, increase acceleration with hardened determination when making a move mid-race, or on a crucial corner late-race whilst in midpack.', isUnique: true, uniqueFor: 'Mejiro Dober (Original)' },
    100511: { id: 100511, name: 'Budding Blossom', description: 'If the user engaged in a challenge on a mid-race corner, increase acceleration when well-positioned late-race at least halfway through the final corner.', isUnique: true, uniqueFor: 'Nishino Flower (Original)' },
    110611: { id: 110611, name: 'Louder! Tracen Cheer!', description: 'If the user stays toward the very back during the first half of the race without being rushed, unleash fighting spirit to increase acceleration on the final straight.', isUnique: true, uniqueFor: 'King Halo (Cheerleader)' },
    200343: { id: 200343, name: 'Corner Acceleration ×', description: 'Moderately decrease acceleration on a corner with awkward turning.', isUnique: false, uniqueFor: '' },
    200452: { id: 200452, name: 'Prudent Positioning', description: 'Increase navigation early-race.', isUnique: false, uniqueFor: '' },
    200502: { id: 200502, name: 'Go with the Flow', description: 'Moderately increase navigation late-race.', isUnique: false, uniqueFor: '' },
    201002: { id: 201002, name: 'Meticulous Measures', description: 'Moderately prepare to make for the finish line for a medium duration mid-race. (Sprint)', isUnique: false, uniqueFor: '' },
    201132: { id: 201132, name: 'Thunderbolt Step', description: 'Moderately avoid becoming surrounded for a medium duration when positioned toward the back mid-race. (Medium)', isUnique: false, uniqueFor: '' },
    201262: { id: 201262, name: 'Dodging Danger', description: 'Moderately avoid becoming surrounded early-race. (Front Runner)', isUnique: false, uniqueFor: '' },
    201682: { id: 201682, name: 'Forward, March!', description: 'Moderately prepare to aim for the front late-race. (Dirt)', isUnique: false, uniqueFor: '' },
    200451: { id: 200451, name: 'Center Stage', description: 'Greatly increase navigation early-race.', isUnique: false, uniqueFor: '' },
    200501: { id: 200501, name: 'Lane Legerdemain', description: 'Increase navigation late-race.', isUnique: false, uniqueFor: '' },
    201001: { id: 201001, name: 'Perfect Prep!', description: 'Prepare to make for the finish line for a medium duration mid-race. (Sprint)', isUnique: false, uniqueFor: '' },
    201131: { id: 201131, name: 'Lightning Step', description: 'Avoid becoming surrounded for a medium duration when positioned toward the back mid-race. (Medium)', isUnique: false, uniqueFor: '' },
    201261: { id: 201261, name: 'Sixth Sense', description: 'Avoid becoming surrounded early-race. (Front Runner)', isUnique: false, uniqueFor: '' },
    201681: { id: 201681, name: 'Lead the Charge!', description: 'Prepare to aim for the front late-race. (Dirt)', isUnique: false, uniqueFor: '' },
    200432: { id: 200432, name: 'Focus', description: 'Slightly decrease time lost to slow starts.', isUnique: false, uniqueFor: '' },
    200431: { id: 200431, name: 'Concentration', description: 'Decrease time lost to slow starts.', isUnique: false, uniqueFor: '' },
    200433: { id: 200433, name: 'Gatekept', description: 'Moderately increase time lost to slow starts.', isUnique: false, uniqueFor: '' },
    1100011: { id: 1100011, name: 'Feelin\' a Bit Silly', description: 'Greatly decrease the racer\'s proficiency in starting races. Effects include slow starts and reduced starting acceleration. Removed at the end of the Career playthrough.', isUnique: false, uniqueFor: '' },
    202141: { id: 202141, name: 'You\'re Not the Boss of Me!', description: 'Increase time lost to slow starts and moderately decrease Wit.', isUnique: false, uniqueFor: '' },
    201122: { id: 201122, name: 'Hawkeye', description: 'Moderately widen field of view with heightened observation early-race. (Medium)', isUnique: false, uniqueFor: '' },
    201432: { id: 201432, name: 'Studious', description: 'Slightly widen field of view with heightened observation mid-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    201472: { id: 201472, name: 'I Can See Right Through You', description: 'Slightly widen field of view with situational awareness when moving sideways. (End Closer)', isUnique: false, uniqueFor: '' },
    201502: { id: 201502, name: 'Strategist', description: 'Slightly widen field of view when positioned toward the back late-race. (End Closer)', isUnique: false, uniqueFor: '' },
    201121: { id: 201121, name: 'Clairvoyance', description: 'Widen field of view with heightened observation early-race. (Medium)', isUnique: false, uniqueFor: '' },
    201431: { id: 201431, name: 'The Bigger Picture', description: 'Widen field of view with heightened observation mid-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    201471: { id: 201471, name: 'The Coast Is Clear!', description: 'Moderately widen field of view with situational awareness when moving sideways. (End Closer)', isUnique: false, uniqueFor: '' },
    201501: { id: 201501, name: 'Crusader', description: 'Widen field of view when positioned toward the back late-race. (End Closer)', isUnique: false, uniqueFor: '' },
    210012: { id: 210012, name: 'Ignited Spirit SPD', description: 'Burn bright with team spirit, slightly increasing velocity in proportion to the total Speed of racing team members mid-race.', isUnique: false, uniqueFor: '' },
    210042: { id: 210042, name: 'Ignited Spirit GUTS', description: 'Burn bright with team spirit, very slightly increasing vigor in proportion to the total Guts of racing team members late-race.', isUnique: false, uniqueFor: '' },
    210011: { id: 210011, name: 'Burning Spirit SPD', description: 'Burn bright with team spirit, increasing velocity in proportion to the total Speed of racing team members mid-race.', isUnique: false, uniqueFor: '' },
    210041: { id: 210041, name: 'Burning Spirit GUTS', description: 'Burn bright with team spirit, increasing vigor in proportion to the total Guts of racing team members late-race.', isUnique: false, uniqueFor: '' },
    210022: { id: 210022, name: 'Ignited Spirit STA', description: 'Burn bright with team spirit, slightly recovering endurance in proportion to the total Stamina of racing team members mid-race.', isUnique: false, uniqueFor: '' },
    210021: { id: 210021, name: 'Burning Spirit STA', description: 'Burn bright with team spirit, recovering endurance in proportion to the total Stamina of racing team members mid-race.', isUnique: false, uniqueFor: '' },
    210032: { id: 210032, name: 'Ignited Spirit PWR', description: 'Burn bright with team spirit, slightly increasing acceleration in proportion to the total Power of racing team members late-race.', isUnique: false, uniqueFor: '' },
    210031: { id: 210031, name: 'Burning Spirit PWR', description: 'Burn bright with team spirit, increasing acceleration in proportion to the total Power of racing team members late-race.', isUnique: false, uniqueFor: '' },
    210052: { id: 210052, name: 'Ignited Spirit WIT', description: 'Burn bright with team spirit, slightly increasing strategic navigation for a medium duration in proportion to the total Wit of racing team members early-race.', isUnique: false, uniqueFor: '' },
    210051: { id: 210051, name: 'Burning Spirit WIT', description: 'Burn bright with team spirit, increasing strategic navigation for a medium duration in proportion to the total Wit of racing team members early-race.', isUnique: false, uniqueFor: '' },
    210062: { id: 210062, name: 'Glittering Star', description: 'Very slightly control breathing and kick forward in the second half of the race. Effect is increased in proportion to number of career wins.', isUnique: false, uniqueFor: '' },
    210061: { id: 210061, name: 'Radiant Star', description: 'Control breathing and kick forward in the second half of the race. Effect is increased in proportion to number of career wins.', isUnique: false, uniqueFor: '' },
    200851: { id: 200851, name: 'Hesitant Front Runners', description: 'Slightly decrease velocity of front runners late-race.', isUnique: false, uniqueFor: '' },
    200881: { id: 200881, name: 'Hesitant Pace Chasers', description: 'Slightly decrease velocity of pace chasers late-race.', isUnique: false, uniqueFor: '' },
    200911: { id: 200911, name: 'Hesitant Late Surgers', description: 'Slightly decrease velocity of late surgers late-race.', isUnique: false, uniqueFor: '' },
    200941: { id: 200941, name: 'Hesitant End Closers', description: 'Slightly decrease velocity of end closers late-race.', isUnique: false, uniqueFor: '' },
    201012: { id: 201012, name: 'Intimidate', description: 'Moderately intimidate runners behind when positioned toward the front early-race. (Sprint)', isUnique: false, uniqueFor: '' },
    201082: { id: 201082, name: 'Speed Eater', description: 'Slightly steal velocity from runners behind when positioned toward the front mid-race. (Mile)', isUnique: false, uniqueFor: '' },
    201152: { id: 201152, name: 'Tether', description: 'Slightly decrease velocity of runners ahead when positioned toward the back late-race. (Medium)', isUnique: false, uniqueFor: '' },
    201512: { id: 201512, name: 'Intense Gaze', description: 'Slightly unnerve runners in focus late-race. (End Closer)', isUnique: false, uniqueFor: '' },
    201081: { id: 201081, name: 'Greed for Speed', description: 'Moderately steal velocity from runners behind when positioned toward the front mid-race. (Mile)', isUnique: false, uniqueFor: '' },
    201151: { id: 201151, name: 'Dominator', description: 'Decrease velocity of runners ahead when positioned toward the back late-race. (Medium)', isUnique: false, uniqueFor: '' },
    201511: { id: 201511, name: 'Petrifying Gaze', description: 'Unnerve runners in focus late-race. (End Closer)', isUnique: false, uniqueFor: '' },
    201011: { id: 201011, name: 'Adored by All', description: 'Intimidate runners behind when positioned toward the front early-race. (Sprint)', isUnique: false, uniqueFor: '' },
    201092: { id: 201092, name: 'Opening Gambit', description: 'Slightly dull movement for runners ahead when positioned toward the back early-race. (Mile)', isUnique: false, uniqueFor: '' },
    201302: { id: 201302, name: 'Restart', description: 'Slightly dull movement for runners ahead when not in the lead early-race. (Front Runner)', isUnique: false, uniqueFor: '' },
    201091: { id: 201091, name: 'Battle Formation', description: 'Dull movement for runners ahead when positioned toward the back early-race. (Mile)', isUnique: false, uniqueFor: '' },
    200791: { id: 200791, name: 'Frenzied Front Runners', description: 'Increase time needed for front runners to calm down when they become rushed.', isUnique: false, uniqueFor: '' },
    200801: { id: 200801, name: 'Frenzied Pace Chasers', description: 'Increase time needed for pace chasers to calm down when they become rushed.', isUnique: false, uniqueFor: '' },
    200811: { id: 200811, name: 'Frenzied Late Surgers', description: 'Increase time needed for late surgers to calm down when they become rushed.', isUnique: false, uniqueFor: '' },
    200821: { id: 200821, name: 'Frenzied End Closers', description: 'Increase time needed for end closers to calm down when they become rushed.', isUnique: false, uniqueFor: '' },
    200771: { id: 200771, name: 'Trick (Front)', description: 'Slightly increase fatigue for rushed runners behind when positioned toward the front mid-race.', isUnique: false, uniqueFor: '' },
    200781: { id: 200781, name: 'Trick (Rear)', description: 'Slightly increase fatigue for rushed runners ahead when positioned toward the back mid-race.', isUnique: false, uniqueFor: '' },
    200831: { id: 200831, name: 'Subdued Front Runners', description: 'Slightly increase fatigue for front runners early-race.', isUnique: false, uniqueFor: '' },
    200841: { id: 200841, name: 'Flustered Front Runners', description: 'Slightly increase fatigue for front runners mid-race.', isUnique: false, uniqueFor: '' },
    200861: { id: 200861, name: 'Subdued Pace Chasers', description: 'Slightly increase fatigue for pace chasers early-race.', isUnique: false, uniqueFor: '' },
    200871: { id: 200871, name: 'Flustered Pace Chasers', description: 'Slightly increase fatigue for pace chasers mid-race.', isUnique: false, uniqueFor: '' },
    200891: { id: 200891, name: 'Subdued Late Surgers', description: 'Slightly increase fatigue for late surgers early-race.', isUnique: false, uniqueFor: '' },
    200901: { id: 200901, name: 'Flustered Late Surgers', description: 'Slightly increase fatigue for late surgers mid-race.', isUnique: false, uniqueFor: '' },
    200921: { id: 200921, name: 'Subdued End Closers', description: 'Slightly increase fatigue for end closers early-race.', isUnique: false, uniqueFor: '' },
    200931: { id: 200931, name: 'Flustered End Closers', description: 'Slightly increase fatigue for end closers mid-race.', isUnique: false, uniqueFor: '' },
    201022: { id: 201022, name: 'Stop Right There!', description: 'Slightly cause panic in and very slightly dull movement for runners ahead when positioned toward the back early-race. (Sprint)', isUnique: false, uniqueFor: '' },
    201162: { id: 201162, name: 'Murmur', description: 'Slightly disturb runners directly ahead mid-race. (Medium)', isUnique: false, uniqueFor: '' },
    201222: { id: 201222, name: 'Stamina Eater', description: 'Very slightly steal endurance from runners ahead when positioned toward the back mid-race. (Long)', isUnique: false, uniqueFor: '' },
    201442: { id: 201442, name: 'Sharp Gaze', description: 'Slightly startle other runners late-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    201021: { id: 201021, name: 'You\'ve Got No Shot', description: 'Cause panic in and moderately dull movement for runners ahead when positioned toward the back early-race. (Sprint)', isUnique: false, uniqueFor: '' },
    201161: { id: 201161, name: 'Mystifying Murmur', description: 'Disturb runners directly ahead mid-race. (Medium)', isUnique: false, uniqueFor: '' },
    201221: { id: 201221, name: 'Stamina Siphon', description: 'Slightly steal endurance from runners ahead when positioned toward the back mid-race. (Long)', isUnique: false, uniqueFor: '' },
    201441: { id: 201441, name: 'All-Seeing Eyes', description: 'Startle other runners late-race. (Late Surger)', isUnique: false, uniqueFor: '' },
    200772: { id: 200772, name: 'Tantalizing Trick', description: 'Increase fatigue for rushed runners behind when positioned toward the front mid-race.', isUnique: false, uniqueFor: '' },
    201232: { id: 201232, name: 'Smoke Screen', description: 'Moderately narrow the field of view for runners ahead late-race. (Long)', isUnique: false, uniqueFor: '' },
    201372: { id: 201372, name: 'Disorient', description: 'Slightly narrow the field of view for runners behind when positioned toward the front late-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    201231: { id: 201231, name: 'Illusionist', description: 'Narrow the field of view for runners ahead late-race. (Long)', isUnique: false, uniqueFor: '' },
    201371: { id: 201371, name: 'Dazzling Disorientation', description: 'Moderately narrow the field of view for runners behind when positioned toward the front late-race. (Pace Chaser)', isUnique: false, uniqueFor: '' },
    202051: { id: 202051, name: 'Runaway', description: 'Attempt to gain an especially large lead and keep it until the finish. (Front Runner)', isUnique: false, uniqueFor: '' },
    1000011: { id: 1000011, name: 'Carnival Bonus', description: 'Increase attributes by +{0}％ in the Racing Carnival. {1}％ chance to also raise runner\'s mood to Great. This skill will disappear when the event ends.', isUnique: false, uniqueFor: '' },
    1000012: { id: 1000012, name: 'Carnival Bonus', description: 'Increase attributes by +{0}％ in the Racing Carnival. {1}％ chance to also raise runner\'s mood to Great. This skill will disappear when the event ends.', isUnique: false, uniqueFor: '' },
    202061: { id: 202061, name: 'Best in Japan', description: 'Everyone\'s expectations strongly inspire the user, increasing velocity on the final corner. (Long)', isUnique: false, uniqueFor: '' }
};

export function getSkillName(id: number): string {
    return SKILL_DICT[id]?.name || `Skill ${id}`;
}

export function getSkillDescription(id: number): string {
    return SKILL_DICT[id]?.description || '';
}

export function getUniqueSkillForCharacter(charName: string): number[] {
    return Object.values(SKILL_DICT)
        .filter(s => s.isUnique && s.uniqueFor?.includes(charName))
        .map(s => s.id);
}
